### ISSUE TITLE
Build to demo

### ISSUE THREAD

**Issue by svenresch** [percysnoodle/SGBDrillDownController#1]
Just did a clone of your repo to try and build and run the demo. Opening and building both the Xcode project and workspace fails with various errors. Any chance you can try doing the same to fix or suggest a workaround?

Thx! Looking forward to checking your project out!

**Comment by percysnoodle** [comment]
Hi Sven,

What were the errors?

**Comment by percysnoodle** [comment]
Do you have cocoapods installed? Have you run `pod install`?

**Comment by Mallox51** [comment]
Hi,

Same thing is happening for me. Cloned it with github's "clone in desktop" button. Then i went to the project's directory and launched `pod install`

> Analyzing dependencies
> CocoaPods 0.22.2 is available.
> Downloading dependencies
> Installing KIF (0.0.1)
> Generating Pods project
> Integrating client project

Then a launched the xcworkspace and try to compile. There are 14 errors.

> SGBDrillDownController.m:42:64: Cannot find protocol declaration for 'UIToolbarDelegate'; did you mean 'UITabBarDelegate'?
> SGBDrillDownController.m:1319:4: Expected a type
> SGBDrillDownController.m:1319:37: Cannot find protocol declaration for 'UIBarPositioning'
> SGBDrillDownController.m:262:22: Property 'delegate' not found on object of type 'UIToolbar *'
> SGBDrillDownController.m:274:23: Property 'delegate' not found on object of type 'UIToolbar *'
> SGBDrillDownController.m:355:22: Property 'bottomLayoutGuide' not found on object of type 'SGBDrillDownController *'
> SGBDrillDownController.m:403:25: Property 'bottomLayoutGuide' not found on object of type 'SGBDrillDownController *'
> SGBDrillDownController.m:1321:85: Use of undeclared identifier 'UIBarPositionTopAttached'
> SGBDrillDownController.m:1322:73: Use of undeclared identifier 'UIBarPositionBottom'; did you mean 'UIToolbarPositionBottom'?
> SGBDrillDownController.m:1322:73: Implicit conversion of 'NSInteger' (aka 'int') to 'id' is disallowed with ARC
> SGBDrillDownController.m:1322:73: Incompatible integer to pointer conversion returning 'NSInteger' (aka 'int') from a function with result type 'id'
> SGBDrillDownController.m:1323:12: Use of undeclared identifier 'UIBarPositionAny'; did you mean 'UIToolbarPositionAny'?
> SGBDrillDownController.m:1323:12: Implicit conversion of 'NSInteger' (aka 'int') to 'id' is disallowed with ARC```

Can you help us ? Thx a lot!

**Comment by percysnoodle** [comment]
Ah - looks like I've pushed work from the iOS7 branch to master - oops!  I've rolled master back to the last iOS6 commit.  If you clone again now it you should be able to get it to build.  Sorry about that!

**Comment by svenresch** [comment]
Awesome... builds fine now. Thx much!

**Comment by percysnoodle** [comment]
Great! No worries.

**Comment by percysnoodle** [comment]
On 16 Jul 2013, at 17:38, Sven notifications@github.com wrote:

> Simon (percysnoodle)... Any chance you'd be available to ask some questions? sven@logicopolis.com

Go ahead…

## 

Simon
