### ISSUE TITLE
Use UINavigationController as right placeholder is not working

### ISSUE THREAD

**Issue by ipeisong** [percysnoodle/SGBDrillDownController#4]
The rootView won't load. Only an empty UINavigationController is showing.

BTW, is there any docs or tutorials? Thanks.

**Comment by percysnoodle** [comment]
I'll take a look at this - I suspect it's to do with missing calls to `begin/endAppearanceTransition:` - although I'm not sure why you'd want to use a UINavigationController as the right placeholder - why not push your controllers onto the SGBDrillDownController?

There aren't any documents or tutorials, although I do intend to expand on the Readme.

**Comment by ipeisong** [comment]
What I need is the default right view controller to be a navigation controller.

I tried pushViewController but left view and right view both gone empty. I'm not sure how I can get what I want. Thanks.

**Comment by percysnoodle** [comment]
OK, but why do you need a navigation controller on the right?  If you do need that, what does SGBDrillDownController give you that UISplitViewController doesn't?

Could you describe your setup in more detail?  How are you initialising the controllers?

**Comment by ipeisong** [comment]
The code is like:

``` Objective-C
    UIViewController *v1 = [roSettingsViewController new];
    UIViewController *v2 = [roControlViewController new];

    UINavigationController *n1 = [self wrapViewController:v1];

    self.drillDownController = [SGBDrillDownController new];
    self.drillDownController.leftControllerWidth = 230;
    self.drillDownController.leftPlaceholderController = v2;
    self.drillDownController.rightPlaceholderController = n1;
```

What I need is the left view controller should stay unchanged, the right view controller will change on selection of cell in left view.
Then the right view controller may click deep into multi levels of view controllers. For example, list -> details -> agreement -> payment. That's why I need navigation controller on the right side.

Thanks.

**Comment by percysnoodle** [comment]
It sounds like you'd be better off with a [UISplitViewController](https://developer.apple.com/LIBRARY/IOS/documentation/UIKit/Reference/UISplitViewController_class/Reference/Reference.html), since you're not using the SGBDrillDownController to drill down at all.
