### ISSUE TITLE
Crash when using UICollectionViewController

### ISSUE THREAD

**Issue by guilhermearaujo** [percysnoodle/SGBDrillDownController#7]
I am trying to implement a UICollectionViewController as the right placeholder VC, but it crashes with the message:

```
2014-01-09 10:12:37.453 SGBDrillDownControllerDemo[2038:70b] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Auto Layout still required after sending -viewDidLayoutSubviews to the view controller. SGBDrillDownController's implementation needs to send -layoutSubviews to the view to invoke auto layout.'
```

I tried to solve it by changing this part of SGBDrillDownController.m:

``` Objective-c
- (void)viewDidLayoutSubviews
{
    if (self.suspendLayout) return;
    [self performLayout];
    [self.view layoutSubviews]; // Add this to line 473
}
```

This way, the app stops crashing, but if I rotate the device, the collection view is laid out incorrectly:
![ios simulator screen shot jan 9 2014 10 18 08 am](https://f.cloud.github.com/assets/1733143/1877494/3beeaa36-7928-11e3-9140-4b8f4616c0d5.png)

![ios simulator screen shot jan 9 2014 10 18 05 am](https://f.cloud.github.com/assets/1733143/1877495/3bf28a3e-7928-11e3-90c7-ec85aaefa9aa.png)

This is how the placeholder VC is loaded, on the demo app delegate file:

``` Objective-c
SGBListViewController *listVC = [[SGBListViewController alloc] initWithNibName:@"SGBListViewController" bundle:nil];
drillDownController.rightPlaceholderController = listVC;
```

**Comment by percysnoodle** [comment]
Ugh, autolayout.

How have you set the collection controller up?  Which view has the orange background?

**Comment by guilhermearaujo** [comment]
I implemented the minimum necessary:

``` Objective-c
- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath;
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView *)collectionView;
- (NSInteger)collectionView:(UICollectionView *)collectionView numberOfItemsInSection:(NSInteger)section;
```

The orange background is the collection view's background.

**Comment by percysnoodle** [comment]
Thanks.  Where do you set the background?  I just want to confirm whether it's definitely the controller's view.

**Comment by guilhermearaujo** [comment]
Background is set on the Nib file.

I've commented line 22 on `SGBDrillDownContainerView.m`:

``` Objective-c
self.translatesAutoresizingMaskIntoConstraints = NO;
```

Seems that it worked, but I don't know yet if this is gonna break the layout when Autolayout is not being used.

**Comment by percysnoodle** [comment]
OK, great - let me know how that goes for you and I'll investigate whether it breaks anything for us.

**Comment by jcoleman** [comment]
I believe all that's needed is the addition of `[self.view layoutSubviews];` to `viewDidLayoutSubviews`. As to @guilhermearaujo's problems with the subsequent layout being incorrect, I don't believe that that's a bug with how auto layout interacts with the drill down controller, but with his auto layout constraints. I'm also using auto layout, encountered the same exception, and adding that line (as the error message suggests) fixed the issue without causing any different layout than what I had before adding that line.

**Comment by jcoleman** [comment]
Also, is there a reason you don't call `[super viewDidLayoutSubviews];`?

**Comment by percysnoodle** [comment]
@jcoleman adding `[self.view layoutSubviews];` sounds good.  There's no reason why I didn't call `[super viewDidLayoutSubviews]'`, it's just an oversight.

**Comment by percysnoodle** [comment]
I've added the calls to `layoutSubviews` and `viewDidLayoutSubviews` in v1.1.1.  @guilhermearaujo - Please could you test with your app?

**Comment by guilhermearaujo** [comment]
That seemed to work!

**Comment by percysnoodle** [comment]
Great to hear!
